export default dataArray = [
  { name: "Jarrett Parker", mail: "Jarrett.Parker@hotmail.com" },
  { name: "Brandyn Ebert", mail: "Brandyn45@gmail.com" },
  { name: "Melody Quigley", mail: "Melody.Quigley49@yahoo.com" },
  { name: "Joyce Schimmel", mail: "Joyce_Schimmel@hotmail.com" },
  { name: "Keely Grimes", mail: "Keely_Grimes15@hotmail.com" },
  { name: "Amelia Kovacek", mail: "Amelia_Kovacek55@hotmail.com" },
  { name: "Simeon Hilll Sr.", mail: "Simeon24@hotmail.com" },
  { name: "Frederik Kozey", mail: "Frederik10@yahoo.com" },
  { name: "Rey Hickle", mail: "Rey93@gmail.com" },
  { name: "Abigayle Hayes", mail: "Abigayle_Hayes@hotmail.com" },
  { name: "Clifton MacGyver", mail: "Clifton76@hotmail.com" },
  { name: "Jimmy Moore", mail: "Jimmy_Moore34@gmail.com" },
  { name: "Elyssa Stroman", mail: "Elyssa_Stroman@gmail.com" },
  { name: "Amara Harvey", mail: "Amara_Harvey@hotmail.com" },
  { name: "Columbus Braun", mail: "Columbus.Braun80@gmail.com" },
  { name: "Edna Ullrich", mail: "Edna51@yahoo.com" },
  { name: "Mr. Minnie Conroy", mail: "Minnie.Conroy@gmail.com" },
  { name: "Letha Moen", mail: "Letha.Moen53@yahoo.com" },
  { name: "Suzanne Feeney", mail: "Suzanne_Feeney54@yahoo.com" },
  { name: "Sophie Bartell I", mail: "Sophie10@hotmail.com" },
  { name: "Raphael Schaefer", mail: "Raphael9@gmail.com" },
  { name: "Alexandra Marks", mail: "Alexandra39@gmail.com" },
  { name: "Bart Runolfsdottir", mail: "Bart_Runolfsdottir@hotmail.com" },
  { name: "Kathryn Waelchi", mail: "Kathryn_Waelchi@yahoo.com" },
  { name: "Mr. Johathan Pollich", mail: "Johathan51@gmail.com" },
  { name: "Maximillia Beer", mail: "Maximillia.Beer@gmail.com" },
  { name: "Shashika Raveen", mail: "iamsrylk@gmail.com" },
  // { name: "l", mail: "" },
  // { name: "l", mail: "" },
];
