export default dataArray = [
  { name: "Robert", mail: "robert@robert.robert" },
  { name: "Bryan", mail: "robert@robert.robert" },
  { name: "Vicente", mail: "robert@robert.robert" },
  { name: "Tristan", mail: "robert@robert.robert" },
  { name: "Marie", mail: "robert@robert.robert" },
  { name: "Onni", mail: "robert@robert.robert" },
  { name: "sophie", mail: "robert@robert.robert" },
  { name: "Brad", mail: "robert@robert.robert" },
  { name: "Samual", mail: "robert@robert.robert" },
  { name: "Omur", mail: "robert@robert.robert" },
  { name: "Ower", mail: "robert@robert.robert" },
  { name: "Awery", mail: "robert@robert.robert" },
  { name: "Ann", mail: "robert@robert.robert" },
  { name: "Jhone", mail: "robert@robert.robert" },
  { name: "z", mail: "robert@robert.robert" },
  { name: "bb", mail: "robert@robert.robert" },
  { name: "cc", mail: "robert@robert.robert" },
  { name: "d", mail: "robert@robert.robert" },
  { name: "e", mail: "robert@robert.robert" },
  { name: "f", mail: "robert@robert.robert" },
  { name: "g", mail: "robert@robert.robert" },
  { name: "h", mail: "robert@robert.robert" },
  { name: "i", mail: "robert@robert.robert" },
  { name: "j", mail: "robert@robert.robert" },
  { name: "k", mail: "robert@robert.robert" },
  { name: "l", mail: "robert@robert.robert" },
];
